<?= $this->partial('common/header.phtml', $this) ?>
<form method="get" action="/index/searchcompany">
    搜尋公司名稱: <input type="text" name="query" id="input_query">
    <button type="submit">搜尋</button>
</form>
<span id="message"></span>

<div class="pagination">
    <ul></ul>
</div>

<table class="table">
    <thead>
        <tr>
            <th>日期</th>
            <th>類別</th>
            <th>機關</th>
            <th>標案名稱</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div class="pagination">
    <ul></ul>
</div>
<script>
var query = <?= json_encode($this->query) ?>;
var page= <?= intval($this->page) ?>;

$.get('/api/serachbycompanyname?query=' + encodeURIComponent(query) + '&page=' + page, function(ret){
    $('tbody').html('');
    $('#message').text('顯示搜尋「' + ret.query + '」結果，共 ' + ret.total_records + ' 筆符合，顯示第 ' + ret.page + ' / ' + ret.total_pages + ' 頁。');

    $('#input_query').val(ret.query);
    $('.pagination ul').html('');
    for (var page = 1; page <= ret.total_pages; page ++) {
        var a_dom = $('<a></a>').attr('href', '/index/search?query=' + encodeURIComponent(query) + '&page=' + page).addClass('page-link').text(page);
        var li_dom = $('<li></li>').addClass('page-item').append(a_dom);
        if (ret.page == page) {
            li_dom.addClass('active');
        }

        $('.pagination ul').append(li_dom);
    }

    for (var i = 0; i < ret.records.length; i ++) {
        var record = ret.records[i];
        var tr_dom = $('<tr></tr>');
        tr_dom.append($('<td></td>').text(record.date));
        tr_dom.append($('<td></td>').text(record.brief.type));
        tr_dom.append($('<td></td>').append($('<a></a>').attr('href', record.unit_url).text(record.unit_name)));
        tr_dom.append($('<td></td>').append($('<a></a>').attr('href', record.url).text(record.brief.title)));
        $('tbody').append(tr_dom);
    }
}, 'json');
</script>
<?= $this->partial('common/footer.phtml', $this) ?>
