<?php
$entities = Entity::search(array('oid' => $this->unit->oid))->order('date DESC');
?>
<?= $this->partial('/common/header.phtml', $this) ?>

<h1>機關名稱：<?= $this->escape($this->unit->name) ?></h1>
<table class="table">
    <thead>
        <tr>
            <th>日期</th>
            <th>類型</th>
            <th>代碼</th>
            <th>標案名稱</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($entities as $entity) { ?>
    <?php $brief = json_decode($entity->brief) ?>
    <tr>
        <td><?= $this->escape($entity->date) ?></td>
        <td><?= $this->escape($brief->type) ?></td>
        <td><?= $this->escape($entity->job_number) ?></td>
        <td><a href="<?= $this->escape($entity->link()) ?>"><?= $this->escape($brief->title) ?></a></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<?= $this->partial('common/footer.phtml', $this) ?>
